<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrVsJit\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrVsJit/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLrVsJit.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLrVsJit\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLrVsJit\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LrVsJit',
    'container.build_id' => 'f6d3fe24',
    'container.build_time' => 1644970038,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrVsJit');
