<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'coach' => [[], ['_controller' => 'App\\Controller\\CoachController::index'], [], [['text', '/coach']], [], []],
    'affichecoach' => [[], ['_controller' => 'App\\Controller\\CoachController::readcoach'], [], [['text', '/affichecoach']], [], []],
    'deletecoach' => [['id'], ['_controller' => 'App\\Controller\\CoachController::deletecoach'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/deletecoach']], [], []],
    'addcoach' => [[], ['_controller' => 'App\\Controller\\CoachController::addcoach'], [], [['text', '/addcoach']], [], []],
    'updatecoach' => [['id'], ['_controller' => 'App\\Controller\\CoachController::updatecoach'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/updatecoach']], [], []],
    'profil_index' => [[], ['_controller' => 'App\\Controller\\ProfilController::index'], [], [['text', '/profil/']], [], []],
    'profil_new' => [[], ['_controller' => 'App\\Controller\\ProfilController::new'], [], [['text', '/profil/new']], [], []],
    'profil_show' => [['id'], ['_controller' => 'App\\Controller\\ProfilController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/profil']], [], []],
    'profil_edit' => [['id'], ['_controller' => 'App\\Controller\\ProfilController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/profil']], [], []],
    'profil_delete' => [['id'], ['_controller' => 'App\\Controller\\ProfilController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/profil']], [], []],
    'simpleutilisateur' => [[], ['_controller' => 'App\\Controller\\SimpleutilisateurController::index'], [], [['text', '/simpleutilisateur']], [], []],
    'affichesimpleutilisateur' => [[], ['_controller' => 'App\\Controller\\SimpleutilisateurController::readsimpleutilisateur'], [], [['text', '/affichesimpleutilisateur']], [], []],
    'deletesimpleutilisateur' => [['id'], ['_controller' => 'App\\Controller\\SimpleutilisateurController::deletesimpleutilisateur'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/deletesimpleutilisateur']], [], []],
    'addUtilisateur' => [[], ['_controller' => 'App\\Controller\\SimpleutilisateurController::addUtilisateur'], [], [['text', '/addUtilisateur']], [], []],
    'updateUtilisateur' => [['id'], ['_controller' => 'App\\Controller\\SimpleutilisateurController::updateUtilisateur'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/updateUtilisateur']], [], []],
    'tournoi' => [[], ['_controller' => 'App\\Controller\\TournoiController::index'], [], [['text', '/tournoi']], [], []],
];
